
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author marcela
 */
public class MarcelaTovar_Lab7P2 extends javax.swing.JFrame {

    /**
     * Creates new form MarcelaTovar_Lab7P2
     */
    public MarcelaTovar_Lab7P2() {
        initComponents();
        try {
            administrarCarpeta.cargarArchivo();
            administrarArchivos.cargarArchivo();
            hpb = new HiloProgressBar(JProgressBar_MiUnidad1);
        } catch (Exception InvalidClassException) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextField_IngreseNombreArchivo = new javax.swing.JTextField();
        JComboBox_ExtensionArchivo = new javax.swing.JComboBox<>();
        JSpinner_tamanioArchivo = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JComboBox_SeleccionarCarpetasArchivo = new javax.swing.JComboBox<>();
        jDialog2 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTextField_IngreseNombreCarpeta = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        JPopUpMenu = new javax.swing.JPopupMenu();
        JMenuItem_Destacado = new javax.swing.JMenuItem();
        JMenuItem_Papelera = new javax.swing.JMenuItem();
        JMenuItem_Descargar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JList_Unidades = new javax.swing.JList<>();
        JProgressBar_pg2 = new javax.swing.JProgressBar();
        JProgressBar_MiUnidad1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JList_2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 231, 214));

        jLabel1.setFont(new java.awt.Font("Autography", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Archivo");

        jLabel2.setText("Ingrese el nombre:");

        jLabel3.setText("Ingrese la extension:");

        jLabel4.setText("Ingrese el tamaño:");

        JComboBox_ExtensionArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".docx", ".pdf", ".png", ".jpg", ".mp4" }));

        JSpinner_tamanioArchivo.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));

        jButton3.setText("Agregar el Archivo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Agregar a una Carpeta");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel7.setText("Seleccionar Carpeta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(JComboBox_ExtensionArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(JTextField_IngreseNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton3)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(JSpinner_tamanioArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JComboBox_SeleccionarCarpetasArchivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTextField_IngreseNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JComboBox_SeleccionarCarpetasArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JComboBox_ExtensionArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton4)))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JSpinner_tamanioArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 231, 214));

        jLabel5.setFont(new java.awt.Font("Autography", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Crear Carpeta");

        jLabel6.setText("Ingrese el nombre:");

        jButton5.setText("Agregar Carpeta");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Agregar a una carpeta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(JTextField_IngreseNombreCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(jComboBox1, 0, 169, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JTextField_IngreseNombreCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JMenuItem_Destacado.setText("Mover a Destacados");
        JMenuItem_Destacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_DestacadoActionPerformed(evt);
            }
        });
        JPopUpMenu.add(JMenuItem_Destacado);

        JMenuItem_Papelera.setText("Mover a Papelera");
        JMenuItem_Papelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuItem_PapeleraMouseClicked(evt);
            }
        });
        JPopUpMenu.add(JMenuItem_Papelera);

        JMenuItem_Descargar.setText("Descargar");
        JMenuItem_Descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_DescargarActionPerformed(evt);
            }
        });
        JPopUpMenu.add(JMenuItem_Descargar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 239, 242));

        JList_Unidades.setFont(new java.awt.Font("American Typewriter", 1, 18)); // NOI18N
        JList_Unidades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Mi Unidad", "Destacados", "Papelera", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        JList_Unidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JList_UnidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JList_Unidades);

        jButton1.setText("Crear Archivo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Carpeta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });

        JList_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JList_2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JList_2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tamaño", "Extension"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JProgressBar_pg2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JProgressBar_MiUnidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(JProgressBar_pg2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JProgressBar_MiUnidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        JComboBox_SeleccionarCarpetasArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        for (Carpeta t : administrarCarpeta.getListaCarpetas()) {
            DefaultComboBoxModel modelo
                    = (DefaultComboBoxModel) JComboBox_SeleccionarCarpetasArchivo.getModel();
            modelo.addElement(t);
            JComboBox_SeleccionarCarpetasArchivo.setModel(modelo);
        }
        
        
        abrir_dialogs(jDialog1);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        administrarArchivos.cargarArchivo();
        String nombre = "", extension = "";
        int tamanio = 0;

        nombre = JTextField_IngreseNombreArchivo.getText();
        extension = (String) JComboBox_ExtensionArchivo.getSelectedItem();
        tamanio = Integer.parseInt(JSpinner_tamanioArchivo.getValue().toString());

        Archivo a = new Archivo(nombre, extension, tamanio);
        String m = a.crearLink();
        a.setLink(m);
        administrarArchivos.getListaArchivos().add(a);
        administrarArchivos.escribirArchivo();
        administrarArchivos.cargarArchivo();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        for (Carpeta t : administrarCarpeta.getListaCarpetas()) {
            DefaultComboBoxModel modelo
                    = (DefaultComboBoxModel) jComboBox1.getModel();
            modelo.addElement(t);
            jComboBox1.setModel(modelo);
        }

        abrir_dialogs(jDialog2);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        administrarCarpeta.cargarArchivo();
        String nombre = "";
        nombre = JTextField_IngreseNombreCarpeta.getText();

        Carpeta c = new Carpeta(nombre);
        String x = c.crearLinkCarpeta();
        c.setLink(x);

        administrarCarpeta.getListaCarpetas().add(c);
        administrarCarpeta.escribirArchivo();
        administrarCarpeta.cargarArchivo();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        administrarCarpeta.cargarArchivo();
        String nombre = "", extension = "";
        int tamanio = 0;

        nombre = JTextField_IngreseNombreArchivo.getText();
        extension = (String) JComboBox_ExtensionArchivo.getSelectedItem();
        tamanio = Integer.parseInt(JSpinner_tamanioArchivo.getValue().toString());

        Archivo a = new Archivo(nombre, extension, tamanio);
        String m = a.crearLink();
        a.setLink(m);
        int pos = JComboBox_SeleccionarCarpetasArchivo.getSelectedIndex();
        administrarCarpeta.getListaCarpetas().get(pos).getArchivos().add(a);
        administrarCarpeta.escribirArchivo();
        administrarCarpeta.cargarArchivo();


    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        administrarCarpeta.cargarArchivo();
        String nombre = "";
        nombre = JTextField_IngreseNombreCarpeta.getText();
        

        Carpeta c = new Carpeta(nombre);
        String x = c.crearLinkCarpeta();
        c.setLink(x);
        int pos = jComboBox1.getSelectedIndex();

        administrarCarpeta.getListaCarpetas().get(pos).getCarpetas().add(c);
        administrarCarpeta.escribirArchivo();
        administrarCarpeta.cargarArchivo();
    }//GEN-LAST:event_jButton6MouseClicked

    private void JList_UnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JList_UnidadesMouseClicked
        // TODO add your handling code here:

        switch (JList_Unidades.getSelectedIndex()) {

            case 0: {
                titulo = "Mi Unidad/";
                JProgressBar_MiUnidad1.setStringPainted(true);
                JProgressBar_MiUnidad1.setString(titulo);
                DefaultListModel list = new DefaultListModel();
                for (Archivo t : administrarArchivos.getListaArchivos()) {
                    if (t.isDestacado() == false && t.isPapelera() == false) {
                        list.addElement(t);
                    }

                }
                for (Carpeta c : administrarCarpeta.getListaCarpetas()) {
                    if (c.isDestacado() == false && c.isPapelera() == false) {
                        list.addElement(c);
                    }

                }
                JList_2.setModel(list);

                break;
            }
            case 1: {
                titulo = "Destacados/";
                JProgressBar_MiUnidad1.setStringPainted(true);
                JProgressBar_MiUnidad1.setString(titulo);
                DefaultListModel list = new DefaultListModel();
                for (Archivo t : administrarArchivos.getListaArchivos()) {
                    if (t.isDestacado() == true && t.isPapelera() == false) {
                        list.addElement(t);
                    }

                }
                for (Carpeta c : administrarCarpeta.getListaCarpetas()) {
                    if (c.isDestacado() == true && c.isPapelera() == false) {
                        list.addElement(c);
                    }

                }
                JList_2.setModel(list);
                break;
            }
            case 2: {
                titulo = "Papelera/";
                JProgressBar_MiUnidad1.setStringPainted(true);
                JProgressBar_MiUnidad1.setString(titulo);
                DefaultListModel list = new DefaultListModel();
                for (Archivo t : administrarArchivos.getListaArchivos()) {
                    if (t.isDestacado() == false && t.isPapelera() == true) {
                        list.addElement(t);
                    }

                }
                for (Carpeta c : administrarCarpeta.getListaCarpetas()) {
                    if (c.isDestacado() == false && c.isPapelera() == true) {
                        list.addElement(c);
                    }

                }
                JList_2.setModel(list);
                break;
            }
            default:
                break;
        }

    }//GEN-LAST:event_JList_UnidadesMouseClicked

    private void JList_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JList_2MouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 3) {
            JPopUpMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_JList_2MouseClicked

    private void JMenuItem_DestacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_DestacadoActionPerformed
        // TODO add your handling code here:
        administrarArchivos.cargarArchivo();
        administrarCarpeta.cargarArchivo();
        for (int i = 0; i < administrarArchivos.getListaArchivos().size(); i++) {
            Object x = administrarArchivos.getListaArchivos().get(i);
            listar.add(x);
        }
        for (int i = 0; i < administrarCarpeta.getListaCarpetas().size(); i++) {
            Object x = administrarCarpeta.getListaCarpetas().get(i);
            listar.add(x);
        }
        if (listar.get(JList_2.getSelectedIndex()) instanceof Archivo) {
            //((Archivo)listar.get(JList_2.getSelectedIndex())).setDestacado(true);
            Archivo c = ((Archivo) listar.get(JList_2.getSelectedIndex()));
            int index = administrarArchivos.getListaArchivos().indexOf(c);
            administrarArchivos.getListaArchivos().get(index).setDestacado(true);
        } else if (listar.get(JList_2.getSelectedIndex()) instanceof Carpeta) {
            //((Carpeta)listar.get(JList_2.getSelectedIndex())).setDestacado(true);
            Carpeta c = ((Carpeta) listar.get(JList_2.getSelectedIndex()));
            int index = administrarCarpeta.getListaCarpetas().indexOf(c);
            administrarCarpeta.getListaCarpetas().get(index).setDestacado(true);
        }

        administrarArchivos.escribirArchivo();
        administrarCarpeta.escribirArchivo();
        administrarArchivos.cargarArchivo();
        administrarCarpeta.cargarArchivo();

    }//GEN-LAST:event_JMenuItem_DestacadoActionPerformed

    private void JMenuItem_PapeleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuItem_PapeleraMouseClicked
        // TODO add your handling code here:
        administrarArchivos.cargarArchivo();
        administrarCarpeta.cargarArchivo();
        for (int i = 0; i < administrarArchivos.getListaArchivos().size(); i++) {
            Object x = administrarArchivos.getListaArchivos().get(i);
            listar.add(x);
        }
        for (int i = 0; i < administrarCarpeta.getListaCarpetas().size(); i++) {
            Object x = administrarCarpeta.getListaCarpetas().get(i);
            listar.add(x);
        }
        if (listar.get(JList_2.getSelectedIndex()) instanceof Archivo) {
            //((Archivo)listar.get(JList_2.getSelectedIndex())).setPapelera(true);
            Archivo c = ((Archivo) listar.get(JList_2.getSelectedIndex()));
            int index = administrarArchivos.getListaArchivos().indexOf(c);
            administrarArchivos.getListaArchivos().get(index).setPapelera(true);
        } else if (listar.get(JList_2.getSelectedIndex()) instanceof Carpeta) {
            //((Carpeta)listar.get(JList_2.getSelectedIndex())).setPapelera(true);
            Carpeta c = ((Carpeta) listar.get(JList_2.getSelectedIndex()));
            int index = administrarCarpeta.getListaCarpetas().indexOf(c);
            administrarCarpeta.getListaCarpetas().get(index).setPapelera(true);
        }

        administrarArchivos.escribirArchivo();
        administrarCarpeta.escribirArchivo();
        administrarArchivos.cargarArchivo();
        administrarCarpeta.cargarArchivo();
    }//GEN-LAST:event_JMenuItem_PapeleraMouseClicked

    private void JMenuItem_DescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_DescargarActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < administrarArchivos.getListaArchivos().size(); i++) {
            Object x = administrarArchivos.getListaArchivos().get(i);
            listar.add(x);
        }
        for (int i = 0; i < administrarCarpeta.getListaCarpetas().size(); i++) {
            Object x = administrarCarpeta.getListaCarpetas().get(i);
            listar.add(x);
        }
        if (listar.get(JList_2.getSelectedIndex()) instanceof Archivo) {
            //((Archivo)listar.get(JList_2.getSelectedIndex())).setPapelera(true);
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

            Archivo c = ((Archivo) listar.get(JList_2.getSelectedIndex()));

            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

            Object[] row = {c.getNombre(), c.getTamanio(), c.getExtension()};
            modelo.addRow(row);

            jTable1.setModel(modelo);

            JProgressBar_MiUnidad1.setStringPainted(true);
            JProgressBar_MiUnidad1.setString(titulo + c.getLink());
            hpb.setTamanio((int) c.getTamanio());
            hpb.start();
        } else if (listar.get(JList_2.getSelectedIndex()) instanceof Carpeta) {
            //((Carpeta)listar.get(JList_2.getSelectedIndex())).setPapelera(true);
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Carpeta c = ((Carpeta) listar.get(JList_2.getSelectedIndex()));
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0);
            }
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

            Object[] row = {c.getNombre()};
            modelo.addRow(row);

            jTable1.setModel(modelo);

            JProgressBar_MiUnidad1.setStringPainted(true);
            String s = (titulo + c.getLink());
            JProgressBar_MiUnidad1.setString(s);
        }

    }//GEN-LAST:event_JMenuItem_DescargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcelaTovar_Lab7P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcelaTovar_Lab7P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcelaTovar_Lab7P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcelaTovar_Lab7P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcelaTovar_Lab7P2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBox_ExtensionArchivo;
    private javax.swing.JComboBox<String> JComboBox_SeleccionarCarpetasArchivo;
    private javax.swing.JList<String> JList_2;
    private javax.swing.JList<String> JList_Unidades;
    private javax.swing.JMenuItem JMenuItem_Descargar;
    private javax.swing.JMenuItem JMenuItem_Destacado;
    private javax.swing.JMenuItem JMenuItem_Papelera;
    private javax.swing.JPopupMenu JPopUpMenu;
    private javax.swing.JProgressBar JProgressBar_MiUnidad1;
    private javax.swing.JProgressBar JProgressBar_pg2;
    private javax.swing.JSpinner JSpinner_tamanioArchivo;
    private javax.swing.JTextField JTextField_IngreseNombreArchivo;
    private javax.swing.JTextField JTextField_IngreseNombreCarpeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void abrir_dialogs(JDialog dialog) {
        dialog.setModal(true);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    //Variables globales
    administrarArchivos administrarArchivos = new administrarArchivos("./archivos.cbm");
    administrarCarpetas administrarCarpeta = new administrarCarpetas("./carpetas.cbm");

    ArrayList listar = new ArrayList();

    String titulo = "/Mi unidad";

    HiloProgressBar hpb;

}
